---
title: "03 - Marker Abundance Temporal Evolution"
---

## Define the input and output paths

```{r}
# input
tse_file <- here::here("data", "processed", "tse_alpha.rds")

# output
out_dir <- here::here("data", "03_marker_abundance")
dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)

# confounders 
confounders <- c(
  "treatment",
  "time_point",
  "gender",
  "risk_group",
  "record_id",
  "age"
)

# formula
mod_formula <- glue::glue(
  "ly ~ treatment * time_point + gender + scale(age, center = TRUE, scale = FALSE) + (1|record_id)"
)
```

## Set-up

```{r}
# load libraries
library(magrittr)
library(patchwork)
suppressPackageStartupMessages(library(tidySingleCellExperiment))

# variables for correlation
populations <- c("CD4+ T cells", "CD8+ T cells", "CD4+ T cell count nadir", "CD4+ CD38+ HLA-DR+ T cells", "CD8+ CD38+ HLA-DR+ T cells")
cytokines <- c("CRP", "IL-6", "TNF-a", "sCD14")
others <- c("HIV viral load", "BMI")
```

## Load TSE Object

```{r}
tse <- readr::read_rds(tse_file)
tse

# expand abbreviations
plt_df <-
  tse %>%
  SummarizedExperiment::colData() %>%
  tibble::as_tibble() %>%
  dplyr::mutate(
    "CD4+ T cells" = CD4,
    "CD4+ T cell count nadir" = CD4_nadir,
    "CD8+ T cells" = CD8,
    "CD4+ CD38+ HLA-DR+ T cells" = CD4_CD38_DR,
    "CD8+ CD38+ HLA-DR+ T cells" = CD8_CD38_DR,
    "IL-6" = IL6,
    "TNF-a" = TNFa,
    "sCD14" = sCD14,
    "HIV viral load" = HIV_VL
  ) 
```

## Define Cytokines and Markers

```{r}
all_markers <- 
  c(populations, cytokines, others) %>% 
  tibble::enframe(value = "marker") %>% 
  dplyr::mutate(unit = dplyr::case_when(
    marker %in% populations ~ "counts/mL", 
    marker %in% c("IL-6", "TNF-a") ~ "pg/mL", 
    marker == "CRP" ~ "mg/mL", 
    marker == "sCD14" ~ "ng/mL", 
    marker == "HIV viral load" ~ "copies/mL",
    marker == "BMI" ~ "kg/m2",
    TRUE ~ NA_character_
  ))
```

## Plot Global Evolution

```{r}
#| message: false
plt_list <- 
  all_markers$marker %>% 
  purrr::set_names() %>% 
  purrr::map(~ {
    # prepare data
    .unit <- all_markers[all_markers$marker == .x, "unit"]
    plt_df <- 
      plt_df %>%
      tidyr::drop_na(dplyr::all_of(.x))%>% 
      dplyr::mutate(time_point = factor(time_point))
     
    # calculate stats
    stats_2 <-
      plt_df %>%
      rstatix::group_by(treatment) %>%
      rstatix::wilcox_test(
        formula = formula(glue::glue("`{.x}` ~ time_point")),
        p.adjust.method = "fdr", 
        detailed = TRUE
      ) %>%
      rstatix::add_significance(output.col = "p.adj.signif") %>%
      rstatix::add_xy_position(x = "time_point", group = "treatment")
      
    # plot
    plt <- 
      plt_df %>% 
      tidyr::drop_na(!!dplyr::sym(.x)) %>% 
      tidyplots::tidyplot(x = time_point, y = !!dplyr::sym(.x), colour = treatment) %>% 
      tidyplots::add_boxplot(show_outliers = FALSE) %>%
      tidyplots::add_data_points_jitter(alpha = 0.4) %>%
      tidyplots::add_test_asterisks(
        method = "wilcox_test", hide_info = TRUE, bracket.nudge.y = 0.05, tip.length = 0.01, hide.ns = FALSE
      ) %>%
      tidyplots::add(ggpubr::stat_pvalue_manual(
        stats_2, label = "p.adj.signif", hide.ns = FALSE, tip.length = 0.01
      )) %>% 
      tidyplots::adjust_x_axis_title("Time Point (weeks)") %>%
      tidyplots::adjust_legend_title("Treatment") %>%
      tidyplots::adjust_y_axis_title(
        glue::glue("{.x} ({.unit})")
      ) %>% 
      tidyplots::adjust_colors(tidyplots::colors_discrete_friendly) 
      
    # save
    plt %>%
      tidyplots::adjust_size(width = 40, height = 40, unit = "mm") %>%
      tidyplots::save_plot(
        here::here(out_dir, glue::glue("temp_abundance_{.x}.pdf")),
        view_plot = FALSE
      )
    
    plt %>% tidyplots::adjust_size(75, 75) %>% tidyplots::adjust_font(8)
  })
```

::: {.panel-tabset}

```{r}
#| results: asis
#| warning: FALSE
names(plt_list) %>% 
  purrr::walk(~ {
    cat("#### ", .x, "\n")
    plot(plt_list[[.x]])
    cat("\n\n")
  })
```

:::

### Plot Zooms

```{r}
plt_list <- list(
  CRP = plt_list[["CRP"]] %>% tidyplots::add(ggforce::facet_zoom(y = CRP < 2)), 
  IL6 = plt_list[["IL-6"]] %>% tidyplots::add(ggforce::facet_zoom(y = `IL-6` < 60)), 
  HIV_VL = plt_list[["HIV viral load"]] %>% tidyplots::add(ggforce::facet_zoom(ylim = c(0, 500))), 
  TNFa = plt_list[["TNF-a"]] %>% tidyplots::add(ggforce::facet_zoom(y = `TNF-a` < 30)), 
  CD4 = plt_list[["CD4+ T cells"]] %>% tidyplots::add(ggforce::facet_zoom(ylim = c(0, 350)))
)

names(plt_list) %>% 
  purrr::walk(~ {
    plt_list[[.x]] %>%
      tidyplots::adjust_size(width = 70, height = 40, unit = "mm") %>%
      tidyplots::save_plot(
        here::here(out_dir, glue::glue("zoom_temp_abundance_{.x}.pdf")),
        view_plot = FALSE
      )
  })

```

::: {.panel-tabset}

```{r}
#| results: asis
#| warning: FALSE
names(plt_list) %>% 
  purrr::walk(~ {
    cat("#### ", .x, "\n")
    plt <- 
      plt_list[[.x]] %>% 
      tidyplots::adjust_size(width = 75, height = 50, unit = "mm")
    plot(plt)
    cat("\n\n")
  })
```

:::

## Plot LMM Ratios

```{r}
#| message: false
plt_list <-
  all_markers$marker[-3] %>%
  purrr::set_names() %>%
  purrr::map(
    ~ {
      .marker <- rlang::sym(.x)
      baseline_tp = "0"

      # prepare data
      plt_df <-
        plt_df %>%
        dplyr::select(dplyr::all_of(c(confounders, .x))) %>%
        dplyr::arrange(record_id, time_point) %>%
        tidyr::drop_na() %>%
        dplyr::mutate(
          dplyr::across(dplyr::where(is.character), as.factor),
          treatment = factor(treatment, levels = c("DRV/r", "DTG")),
          time_point = factor(time_point),
          ly = log2(!!dplyr::sym(.x) + 1e-6)
        )

      # contrasts
      tp_levels <- levels(plt_df$time_point)
      contr_list <- setNames(
        lapply(tp_levels[tp_levels != baseline_tp], function(tp) {
          w <- setNames(rep(0, length(tp_levels)), tp_levels)
          w[tp] <- 1
          w[baseline_tp] <- -1
          w
        }),
        paste0(tp_levels[tp_levels != baseline_tp], " - ", baseline_tp)
      )

      # lmm
      lmm_res <-
        stats::as.formula(mod_formula) %>%
        lmerTest::lmer(data = plt_df)

      # emmeans: changes vs basal inside each treatment
      lon_contrast_df <-
        lmm_res %>%
        emmeans::emmeans(~ time_point | treatment) %>%
        emmeans::contrast(contr_list, adjust = "fdr") %>%
        broom.mixed::tidy(conf.int = TRUE) %>%
        dplyr::mutate(
          contrast_clean = stringr::str_remove_all(contrast, "time_point"),
          time_point = readr::parse_number(contrast_clean) %>%
            as.character() %>%
            as.factor()
        )

      # stub de basal a 0 sin IC
      baseline_stub <-
        emmeans::emmeans(lmm_res, ~ time_point | treatment) %>%
        broom.mixed::tidy() %>%
        dplyr::filter(time_point == baseline_tp) %>%
        dplyr::transmute(
          treatment,
          estimate = 0,
          conf.low = 0,
          conf.high = 0,
          adj.p.value = NA_real_,
          time_point = baseline_tp
        )

      lon_contrast_df <- dplyr::bind_rows(baseline_stub, lon_contrast_df)

      # emmeand by group
      group_contrast_df <-
        lmm_res %>%
        emmeans::emmeans(~ treatment | time_point) %>%
        emmeans::contrast(method = "revpairwise", adjust = "fdr") %>%
        broom.mixed::tidy(conf.int = TRUE) %>%
        dplyr::mutate(p.adj.global = p.adjust(p.value, method = "fdr"))

      # forest plot by group
      forest_plt_group <-
        group_contrast_df %>%
        rstatix::add_significance(p.col = "p.adj.global") %>%
        tidyplots::tidyplot(x = estimate, y = time_point) %>%
        tidyplots::add(geom_pointrange(
          aes(xmin = conf.low, xmax = conf.high),
          alpha = 0.8,
          position = position_dodge(width = 0.6),
          size = 2 / ggplot2::.pt,
          colour = "#252525"
        )) %>%
        tidyplots::add_reference_lines(x = 0) %>%
        tidyplots::add(geom_text(
          aes(
            x = conf.high * 1.2,
            label = dplyr::if_else(
              p.adj.global.signif != "ns",
              p.adj.global.signif,
              ""
            )
          ),
          position = position_dodge(width = 0.6),
          size = 7,
          hjust = 0,
          colour = "black"
        )) %>%
        tidyplots::add(expand_limits(
          x = max(group_contrast_df$conf.high, na.rm = TRUE) * 1.25
        )) %>%
        tidyplots::adjust_x_axis_title(glue::glue(
          "Δ log2({.x}) (DTG - DRV/r)"
        )) %>%
        tidyplots::adjust_y_axis_title("Time point (weeks)") %>%
        tidyplots::adjust_size(75, 75) %>%
        tidyplots::adjust_font(8)

      # Trajectory plot
      traj_plt <-
        lon_contrast_df %>%
        tidyplots::tidyplot(
          x = time_point,
          y = estimate,
          colour = treatment,
          group = treatment
        ) %>%
        tidyplots::add(geom_pointrange(
          aes(ymin = conf.low, ymax = conf.high),
          alpha = 0.8,
          size = 2 / ggplot2::.pt,
          position = position_dodge(width = 1 / ggplot2::.pt)
        )) %>%
        tidyplots::add_line() %>%
        tidyplots::add_reference_lines(y = 0) %>%
        tidyplots::adjust_x_axis_title("Time Point (weeks)") %>%
        tidyplots::adjust_y_axis_title(glue::glue("Δ log2({.x}) vs basal")) %>%
        tidyplots::adjust_legend_title("Treatment") %>%
        tidyplots::adjust_size(75, 75) %>%
        tidyplots::adjust_font(8)

      # plt list
      plt_list <- list(traj_plt = traj_plt, forest_plt_group = forest_plt_group)

      # save
      showtext::showtext_auto()
      names(plt_list) %>%
        purrr::walk(
          ~ {
            plt_list[[.x]] %>%
              tidyplots::adjust_size(width = 40, height = 40, unit = "mm") %>%
              tidyplots::adjust_font(7) %>%
              tidyplots::save_plot(
                here::here(out_dir, glue::glue("lmm_{.x}_{.marker}.pdf")),
                view_plot = FALSE
              )
          }
        )

      list(
        lon_stats = lon_contrast_df %>% dplyr::mutate(metric = .x),
        grp_stats = group_contrast_df %>% dplyr::mutate(metric = .x),
        plt = wrap_plots(plt_list) + plot_layout(guides = "collect")
      )
    }
  )

lon_stats <- plt_list %>% purrr::map_dfr(~ { .x[["lon_stats"]] })
grp_stats <- plt_list %>% purrr::map_dfr(~ { .x[["grp_stats"]] })

readr::write_csv(lon_stats, here::here(out_dir, "lmm_longitudinal_stats.csv"))
readr::write_csv(grp_stats, here::here(out_dir, "lmm_group_stats.csv"))
```

## Plot 

::: {.panel-tabset}

```{r}
#| results: asis
#| warning: FALSE
names(plt_list) %>% 
  purrr::walk(~ {
    cat("#### ", .x, "\n")
    plot(plt_list[[.x]])
    cat("\n\n")
  })
```

:::

## Appendix

### Session Info

```{r}
devtools::session_info()
```

### Contact

- **Analysis Lead:** Francesc Català-Moll
- **Email:** fcatala@irsicaixa.es
- **Institution:** GEM - IrsiCaixa
