---
title: "05 - Differential Abundance Analysis"
---

## Define the input and output paths

```{r}
# input
tse_file <- here::here("data", "processed", "tse_alpha.rds")

# output
out_dir <- here::here("data", "05_diff_abundance")
dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)
```

## Set-up

```{r}
# load libraries
library(magrittr)
library(patchwork)
library(tidyplots)
suppressPackageStartupMessages(library(tidySingleCellExperiment))
```

## Load TSE Object and Transform

```{r}
tse <- 
  readr::read_rds(tse_file) %>% 
  mia::transformAssay(method = "relab") %>% 
  mia::transformAssay(method = "clr", pseudocount = 1) %>% 
  mia::transformAssay(method = "log10", pseudocount = 1)

tse
```

## Differential Abundance Analysis (ANCOMBC2)

### DA Computation

```{r}
ancombc_results <- ANCOMBC::ancombc2( 
  r_plt,
  here::here(out_dir, glue::glue("corr_diff_taxa.pdf")),
  view_plot = FALSE
)

r_plt
```

## Appendix

### Session Info

```{r}
devtools::session_info()
```

### Contact

- **Analysis Lead:** Francesc Català-Moll
- **Email:** fcatala@irsicaixa.es
- **Institution:** GEM - IrsiCaixa
